name: Weekly IT Events Report

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5  # Обновили с v4 до v5
      
    - name: Set up Python
      uses: actions/setup-python@v5  # Оставляем v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run script
      run: python main.py
